---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: demo
  labels:
    app: podinfo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.3
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: podinfo
    spec:
      serviceAccountName: build-robot
      volumes:
      - name: vault-token
        emptyDir:
          medium: Memory
      - name: config
        configMap:
          name: example-vault-agent-config
          items:
          - key: vault-agent-config.hcl
            path: vault-agent-config.hcl
          - key: consul-template-config.hcl
            path: consul-template-config.hcl
      - name: shared-data
        emptyDir: {}

      initContainers:
      - name: init
        image: alpine:3.10
        command:
        - sleep
        - "1"
      - name: vault-agent-auth
        image: vault
        volumeMounts:
        - name: config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /home/vault
        env:
        - name: VAULT_ADDR
          value: https://vault.k8s.oprm.net
        args: ["agent", "-config=/etc/vault/vault-agent-config.hcl"]
      containers:
      - name: consul-template
        image: hashicorp/consul-template:0.20.0-scratch
        imagePullPolicy: Always

        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        - name: config
          mountPath: /etc/consul-template
        - name: shared-data
          mountPath: /etc/secrets
        env:
        - name: HOME
          value: /home/vault
        - name: VAULT_ADDR
          value: https://vault.k8s.oprm.net

        args: ["-config=/etc/consul-template/consul-template-config.hcl"]
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi

      - name: podinfod
        image: stefanprodan/podinfo:1.3.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: PODINFO_UI_COLOR
          value: green
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9898
        readinessProbe:
          httpGet:
            path: /readyz
            port: 9898
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
